version: 2.1

orbs:
  slack: circleci/slack@4.4.4

executors:
  php_7_4:
    docker:
      - image: circleci/php:7.4
  php_8_0:
    docker:
      - image: circleci/php:8.0

jobs:
  build_and_test:
    parameters:
      e:
        type: executor
        default: php_8_0
      cv:
        description: "composer's version"
        type: integer
        default: 2
    executor: << parameters.e >>
    environment:
      # fixes memory error when using composer v1 to run composer update
      COMPOSER_MEMORY_LIMIT: -1
    steps:
      - checkout
      - run:
          name: "Setup composer v<< parameters.cv >>"
          command: >
            sudo composer self-update
            --no-progress
            --clean-backups --<< parameters.cv >>
      - restore_cache:
          keys:
            - composer<< parameters.cv >>-{{ checksum "composer.lock" }}
            - composer<< parameters.cv >>-
      - run:
          name: "Composer update"
          command: composer update
      - run:
          name: "Composer install"
          command: composer install -n --prefer-dist
      - save_cache:
          key: composer<< parameters.cv >>-{{ checksum "composer.lock" }}
          paths:
            - vendor
      - run:
          name: "Validate PHP Platform Requirements"
          command: "composer check-platform-reqs"
      - run:
          name: "Run Unit Tests"
          command: ./vendor/bin/phpunit tests --log-junit tests/_output/test_results.xml
      - run:
          name: "Run PHPCS (coding standards)"
          command: ./vendor/bin/phpcs -n --standard=PSR2 ./app/
      - run:
          name: "Run bach on bach"
          command: php bach composer composer.json
      - store_test_results:
          path: tests/_output
      - store_artifacts:
          path: tests/_output

workflows:
  version: 2
  build_fork:
    jobs:
      - build_and_test:
          e: php_8_0
          filters:
            branches:
              # Forked pull requests have CIRCLE_BRANCH set to pull/XXX
              only: /pull\/[0-9]+/
      - build_and_test:
          e: php_7_4
          cv: 1
          filters:
            branches:
              # Forked pull requests have CIRCLE_BRANCH set to pull/XXX
              only: /pull\/[0-9]+/

  build_origin:
    jobs:
      - build_and_test:
          e: php_8_0
          context:
            - slack_community_oss_fun
          filters:
            branches:
              # Forked pull requests have CIRCLE_BRANCH set to pull/XXX
              ignore: /pull\/[0-9]+/
      - build_and_test:
          e: php_7_4
          cv: 1
          context:
            - slack_community_oss_fun
          filters:
            branches:
              # Forked pull requests have CIRCLE_BRANCH set to pull/XXX
              ignore: /pull\/[0-9]+/

  build_nightly:
    triggers:
      - schedule:
          cron: "35 20 * * *"
          filters:
            branches:
              only: main
    jobs:
      - build_and_test:
          e: php_8_0
          context:
            - slack_community_oss_fun
      - build_and_test:
          e: php_7_4
          cv: 1
          context:
            - slack_community_oss_fun
