version: 2.1
executors:
  php_7_4:
    docker:
      - image: circleci/php:7.4
  php_8_0:
    docker:
      - image: circleci/php:8.0

jobs:
  build_and_test:
    parameters:
      e:
        type: executor
        default: php_8_0
      cv:
        description: "composer's version"
        type: integer
        default: 2
    executor: << parameters.e >>
    steps:
      - checkout
      - run:
          description: "Setup composer v<< parameters.cv >>"
          command: >
            sudo composer self-update
            --no-progress
            --clean-backups --<< parameters.cv >>
      - restore_cache:
          keys:
            - composer<< parameters.cv >>-{{ checksum "composer.lock" }}
            - composer<< parameters.cv >>-
      - run: COMPOSER_MEMORY_LIMIT=-1 composer update
      - run: composer install -n --prefer-dist
      - save_cache:
          key: composer<< parameters.cv >>-{{ checksum "composer.lock" }}
          paths:
            - vendor
      - run: ./vendor/bin/phpunit tests --log-junit tests/_output/test_results.xml
      - run: ./vendor/bin/phpcs -n --standard=PSR2 ./app/
      - run:
          description: "Run bach on bach"
          command: |
            php bach composer composer.json
      - store_test_results:
          path: tests/_output
      - store_artifacts:
          path: tests/_output

workflows:
  version: 2
  workflow:
    jobs:
      - build_and_test:
          e: php_8_0
      - build_and_test:
          e: php_7_4
          cv: 1

  build_nightly:
    triggers:
      - schedule:
          cron: "35 20 * * *"
          filters:
            branches:
              only: main
    jobs:
      - build_and_test:
          e: php_8_0
      - build_and_test:
          e: php_7_4
          cv: 1
